[program:digitalbuilders-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/DigitalBuilders/artisan queue:work redis --sleep=2 --tries=3 --max-time=3600 --timeout=90
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/digitalbuilders-worker.log
stopwaitsecs=3600

[program:digitalbuilders-market-worker]
process_name=%(program_name)s
command=php /var/www/DigitalBuilders/artisan market:poll-requirements
autostart=false
autorestart=false
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/digitalbuilders-market.log
